# [START functions_ci_cd_cloud_build]
steps:
# - name: 'docker.io/library/python:3.10'
#   entrypoint: /bin/sh
  # Run pip install and pytest in the same build step
  # (pip packages won't be preserved in future steps!)
  # args: [-c, 'pip install -r requirements.txt && pytest']
  # dir: 'function/dir/from/repo/root'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'testing-so-metrics-v2', '--gen2' , '--trigger-http', '--runtime', 'python310', '--entry-point', 'main', --region, 'us-central1', '--allow-unauthenticated']
  # dir: 'function/dir/from/repo/root'
# [END functions_ci_cd_cloud_build]
#gcloud functions deploy testing-so-metrics-v1 \
# --gen2 \
# --runtime=python310 \
# --source=. \
# --entry-point=main \
# --trigger-http \
# --allow-unauthenticated